### ISSUE TITLE
getting error: "Cannot resolve package path for: monaco-editor" in windows

### ISSUE THREAD

**Issue by jayant4frndz007** [JeremyRH/storybook-addon-code-editor#41] opened 2024-06-11 19:28 UTC
I am facing this issue when I am running storybook after adding storybook-addon-code-editor on windows but same is running fine on mac-os.

storybook: 8.0.10
storybook-addon-code-editor : 3.0.0
windows: 8

```
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook\main.ts file.

Error: Cannot resolve package path for: 'monaco-editor'.
Entry file: \node_modules\monaco-editor\package.json
    at resolvePackagePath (i:\Projects\Sprint-224\conflict-pepper\pepper\node_modules\storybook-addon-code-editor\dist\cjs\getStaticDirs.js:37:15)
    at getExtraStaticDir (i:\Projects\Sprint-224\conflict-pepper\pepper\node_modules\storybook-addon-code-editor\dist\cjs\getStaticDirs.js:59:22)
    at Object.<anonymous> (i:\Projects\Sprint-224\conflict-pepper\pepper\.storybook\main.ts:17:16)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._compile (\node_modules\esbuild-register\dist\node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.newLoader [as .ts] (\node_modules\esbuild-register\dist\node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
```

**Comment by JeremyRH** [comment] 2024-06-11 23:57
Thank you for reporting this. The issue is with [`getStaticDirs.ts`](https://github.com/JeremyRH/storybook-addon-code-editor/blob/8c3371bab8f8fc22d8ba23ae877a7ee98d364f11/src/getStaticDirs.ts) not handling windows path separators.

I'll have a fix for this in a few hours.

**Comment by JeremyRH** [comment] 2024-06-12 01:17
I did not test this on windows. Please let me know if version 3.0.1 does not fix this.

**Comment by jayant4frndz007** [comment] 2024-06-12 18:17
thank you so much. I have upgraded to version 3.0.1 and its working fine.👍

**Closed** 2024-06-24 18:13 UTC
