### ISSUE TITLE
Error when use additional addons with code editor

### ISSUE THREAD

**Issue by MateuszCieslak** [JeremyRH/storybook-addon-code-editor#2] opened 2023-03-07 13:24 UTC
Hey, 
I have error when trying to configure storybook with live code editor addon. When I do it only with this addon it works fine but when I try to use it with additional then error occurs. I want to have live code editor for story and actions etc.

Storybook 6.5.16

My main.js
```module.exports = {
    stories: findStories(),
    addons: [
        '@storybook/addon-links',
        '@storybook/addon-essentials',
        '@storybook/addon-interactions',
        '@storybook/preset-create-react-app',
        '@storybook/addon-controls',
        'storybook-addon-code-editor'
    ],
    framework: '@storybook/react',
    core: {
        builder: 'webpack5',
    },

    // Configuration from https://github.com/storybookjs/storybook/issues/1493
    webpackFinal: config => {
        config.module.rules.push({
            test: /\.tsx?$/,
            exclude: /node_modules/,
            use: [
                {
                    loader: require.resolve('babel-loader'),
                    options: {
                        presets: [
                            require('@babel/preset-typescript').default,
                            [require('@babel/preset-react').default, { runtime: 'automatic' }],
                            require('@babel/preset-env').default,
                        ],
                    },
                },
            ],
        });

        return config;
    },
}; 
```

Error:
```
vendors-node_modules_(...)_dist_index_es_js-node_modules_storyb-84f65d.manager.bundle.js:109695 
Warning: React has detected a change in the order of Hooks called by Tabs. 
This will lead to bugs and errors if not fixed. For more information,
 read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useEffect                  useEffect
3. useContext                 useState
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by JeremyRH** [comment] 2023-03-08 03:58
Thanks for reporting this. I found how to reproduce the issue.
Use `@storybook/addon-interactions` and `@storybook/addon-controls` and set this story parameter:
```js
story.parameters = {
    controls: { disable: true }
```
This seems like a bug in one of those addons but I'll update storybook-addon-code-editor so it doesn't set that story parameter. It was used to hide the controls tab so it's not a big deal to remove the story parameter.

**Comment by JeremyRH** [comment] 2023-03-08 07:04
Version 1.0.1 is released with (hopefully) the fix. Let me know if you still have issues.

**Comment by JeremyRH** [comment] 2023-03-15 20:17
Your welcome, thanks again for reporting this.

The error in the console is due to the way storybook renders tabs. I think addons can control things with tabs that cause different components to render without React knowing different components are being rendered. I haven't looked deeply into it so can't say for sure. I see the console error without `storybook-addon-code-editor` so I think the issue is with `@storybook/addon-interactions` and `@storybook/addon-controls` and some story parameters being set.

**Closed by JeremyRH** 2023-03-15 20:17 UTC
